# travis file
sudo: required
services:
  - docker
before_install:
  - docker build -t acp-pradhyuman/react-with-docker -f Docker-dev
script:
  - docker run -e CI=true acp-pradhyuman/react-with-docker npm run test -- --coverage
