# travis file
sudo: required
services:
  - docker
before_install:
  - docker build -t acp-pradhyuman/react-with-docker -f Docker-dev .
script:
  - docker run -e CI=true acp-pradhyuman/react-with-docker npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'react with docker'
  env: 'Reactwithdocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-606389448678'
  bucket_path: 'react with docker'
  on:
    branch: main
  access_key_id: $Access_key_ID
  secret_access_key: $Secret_access_key
